### ISSUE TITLE
Feature request: add option to not increment the first selected number

### ISSUE THREAD

**Issue by hagabaka** [narsenico/vscode-progressive-increment#2]
When using this extension, I wish to select a list of numbers, and use the first one as the start of the sequence, without adding 1 to it. So `1 1 1 1` becomes `1 2 3 4` rather than `2 3 4 5`.

When I want to increment a single number, I use a separate extension for it. The current behavior of this extension allows it to handle this use case, but unfortunately it makes creating a sequence a little trickier, because I have to remember to type in `the first number - 1`.

So I hope there could be an option or a separate command to progressively increment / create a sequence, without changing the first selected number.

**Comment by narsenico** [comment]
Added new setting progressive.skipFirstNumber in version 1.0.2
